### ISSUE TITLE
Possible to convert `wat` output to string and display it outside console?

### ISSUE THREAD

**Issue by Trung0246** [igrek51/wat#18]
I have tried `print(str(wat / {"a": 1}))` but it printed `None` instead.

**Comment by thiswillbeyourgithub** [comment]
I'm having issues because wat, instead of returning strings prints on its own and in my particular setup it uses color themes that are invisible: 

![image](https://github.com/user-attachments/assets/9a833c6d-e23e-45dd-93a6-236d9bc4892b)

I think a good fix would be to:
1. Add an attribute "display_mode" that default to "print" but can be "return_string" instead. This way we don't lose the author's work on the display but still make wat usable on all device.
2. Make it so that if "PYTHON_WAT_DISPLAY_MODE='return_string'" exists in the environment, then wat should return strings instead of using its own printer. This would probably require minimal change to the code while still allowing all users to avoid this issue without having to set the display_mode every time (I could just set it in my shell rc file and forget about it)
What do you think?

**Comment by igrek51** [comment]
@Trung0246 Thank you for this idea.
The issue is solved by https://github.com/igrek51/wat/pull/21. This adds `.str` modifier to return the output string instead of printing.
So now you can do:
```python
print(wat.str / {"a": 1})
```

**Comment by igrek51** [comment]
@thiswillbeyourgithub Your idea will be addressed in https://github.com/igrek51/wat/issues/22
