### ISSUE TITLE
Add the object name to the output

### ISSUE THREAD

**Issue by 5trobl** [igrek51/wat#28]
E.g. in case the call is from within a script.
Also in the short version.
Cheers

**Comment by igrek51** [comment]
@5trobl That's an interesting idea. Do you have a specific way of doing this in mind?
I suppose we're talking about reading original variable name passed to a function. If so, it's not so easy to do in Python.

In case we want to read "y" name from snippet:
```python
y = 7
wat / y
```
we'd have to do something hacky and unreliable like https://stackoverflow.com/a/2749857/6772197. Or is there a better way?

Still, this won't work, if we call this on an anonymous, temporary variables:
```python
wat / (2+2)
wat / math.sqrt(4)
```

**Comment by 5trobl** [comment]
Thank you! It works beautifully.

I wonder... why use a modifier at all, rather than by default? If it only shows up for scripts, then you're always going to need it, right?

What about showing it at the top, prior to `value`?

**Comment by igrek51** [comment]
> I wonder... why use a modifier at all, rather than by default? If it only shows up for scripts, then you're always going to need it, right?

Actually, some information would be still displayed in python console when it's enabled. It doesn't show "caller expression", but "caller file" is there. It doesn't say anything useful though. I believe it would be a bit annoying to always see this line:
```
caller file: <stdin>:1
```

Plus, I would have to rewrite most of the unit tests, because test cases would be treated as a script. I know it's not a good argument because it's only about tests, but it makes it all clear and simpler to have it disabled by default. I like to operate on "pure functions".

> What about showing it at the top, prior to value?

yeah, maybe it makes sense to first see where it comes from and then what it is. I'll change that.
