### ISSUE TITLE
Add Todo for Feature Improvements or Bug Fixes

### ISSUE THREAD

**Issue by A-ElMahmi** [igrek51/wat#30]
This is a really cool tool and I'd love to help contribute.

It would be nice if there was a TODO section with planned features or bug fixes that people can choose to work on :)

**Comment by igrek51** [comment]
Thanks for your support.
Personally, I consider TODO comments as a bad practice. Instead, I prefer to keep things to do in Github issues, which I believe is a better place for open discussions.
So keep monitoring [issues](https://github.com/igrek51/wat/issues), which is quite empty by now, since this project is a tiny snippet by design.
